import type { TraceModule, BitGridState } from '../lib/types';

const bits = (value: number) => Array.from({ length: 32 }, (_, i) => (value >>> i) & 1);
export const bitState = (values: Array<[string, number]>, activeBitIndex?: number): BitGridState => ({
  renderer: 'bit-grid', numbers: values.map(([label, value]) => ({ label, value, bits: bits(value) })), activeBitIndex,
});

export const countingBits: TraceModule<{ n: number }> = { renderer: 'bit-grid', inputSchema: { n: { type: 'int', label: 'Maximum number', min: 0, max: 64 } }, defaultInput: { n: 5 }, samples: [{ input: { n: 5 }, expected: [0, 1, 1, 2, 1, 2] }, { input: { n: 2 }, expected: [0, 1, 1] }], run: function* ({ n }, L) { const dp = Array(n + 1).fill(0); yield { line: L('vector<int> dp(n + 1, 0);'), event: 'init', state: bitState([['i', 0]]), vars: { n, dp: '[0]' }, note: 'Start the dynamic-programming count at zero.' }; for (let i = 1; i <= n; i++) { dp[i] = dp[i >> 1] + (i & 1); yield { line: L('dp[i] = dp[i >> 1] + (i & 1);   // reuse previously computed result'), event: 'bit-op', state: bitState([['i', i], ['i >> 1', i >> 1]], i & 1 ? 0 : undefined), vars: { i, previous: dp[i >> 1], value: dp[i] }, note: `Reuse count(${i >> 1}) and add the low bit ${i & 1}.` }; } yield { line: L('return dp;'), event: 'done', state: bitState([['n', n]]), vars: { n, dp: JSON.stringify(dp) }, note: 'Every prefix from 0 through n now has its bit count.', result: dp }; } };

export const powerOfTwo: TraceModule<{ n: number }> = { renderer: 'bit-grid', inputSchema: { n: { type: 'int', label: 'Integer', min: -2147483648, max: 2147483647 } }, defaultInput: { n: 16 }, samples: [{ input: { n: 16 }, expected: true }, { input: { n: 18 }, expected: false }], run: function* ({ n }, L) { const result = n > 0 && (n & (n - 1)) === 0; yield { line: L('return (n & (n - 1)) == 0;   // true only if exactly one bit is set'), event: result ? 'found' : 'done', state: bitState([['n', n], ['n - 1', n - 1]]), vars: { n, result }, note: result ? 'Exactly one bit survives the power-of-two test.' : 'More than one bit is set, so this is not a power of two.', result }; } };

export const powerOfFour: TraceModule<{ n: number }> = { renderer: 'bit-grid', inputSchema: { n: { type: 'int', label: 'Integer', min: 0, max: 2147483647 } }, defaultInput: { n: 16 }, samples: [{ input: { n: 16 }, expected: true }, { input: { n: 8 }, expected: false }], run: function* ({ n }, L) { const oneBit = n > 0 && (n & (n - 1)) === 0; const evenPosition = (n & 0xaaaaaaaa) === 0; const result = oneBit && evenPosition; yield { line: L('return isPowerOfTwo && atEvenPosition;'), event: 'done', state: bitState([['n', n], ['mask', 0xaaaaaaaa]]), vars: { n, oneBit, evenPosition, result }, note: `Power-of-two=${oneBit}; its set bit is at an even position=${evenPosition}.`, result }; } };

export const singleNumber: TraceModule<{ nums: number[] }> = { renderer: 'bit-grid', inputSchema: { nums: { type: 'int-array', label: 'Pairs with one unique value', min: 1, max: 16 } }, defaultInput: { nums: [4, 1, 2, 1, 2] }, samples: [{ input: { nums: [4, 1, 2, 1, 2] }, expected: 4 }, { input: { nums: [2, 2, 1] }, expected: 1 }], run: function* ({ nums }, L) { let result = 0; for (const num of nums) { result ^= num; yield { line: L('result ^= num;   // duplicates cancel out (x ^ x = 0)'), event: 'bit-op', state: bitState([['result', result], ['num', num]]), vars: { num, result }, note: `XOR cancels matching pairs; accumulator is ${result}.` }; } yield { line: L('return result;'), event: 'done', state: bitState([['unique', result]]), vars: { result }, note: `The uncancelled value is ${result}.`, result }; } };

export const singleNumberII: TraceModule<{ nums: number[] }> = { renderer: 'bit-grid', inputSchema: { nums: { type: 'int-array', label: 'Triples with one unique value', min: 1, max: 16 } }, defaultInput: { nums: [2, 2, 3, 2] }, samples: [{ input: { nums: [2, 2, 3, 2] }, expected: 3 }, { input: { nums: [0, 1, 0, 1, 0, 1, 99] }, expected: 99 }], run: function* ({ nums }, L) { let result = 0; for (let bit = 0; bit < 32; bit++) { const sum = nums.reduce((total, num) => total + ((num >>> bit) & 1), 0); if (sum % 3 !== 0) result |= (1 << bit); yield { line: L('if (sum % 3 != 0) {'), event: 'bit-op', state: bitState([['result', result], ['bit', 1 << bit]], bit), vars: { bit, sum, result }, note: `Bit ${bit} appears ${sum} times; keep its remainder modulo three.` }; } yield { line: L('return result;'), event: 'done', state: bitState([['unique', result]]), vars: { result }, note: 'Bits with nonzero remainder reconstruct the unique value.', result }; } };

export const missingNumber: TraceModule<{ nums: number[] }> = { renderer: 'bit-grid', inputSchema: { nums: { type: 'int-array', label: 'Values from 0 through n', min: 1, max: 16 } }, defaultInput: { nums: [3, 0, 1] }, samples: [{ input: { nums: [3, 0, 1] }, expected: 2 }, { input: { nums: [0, 1] }, expected: 2 }], run: function* ({ nums }, L) { let result = nums.length; for (let i = 0; i < nums.length; i++) { result ^= i ^ nums[i]; yield { line: L('result ^= i ^ nums[i];         // cancel index i with value nums[i]'), event: 'bit-op', state: bitState([['result', result], ['value', nums[i]]]), vars: { i, value: nums[i], result }, note: `Cancel index ${i} against value ${nums[i]}; only the missing value remains.` }; } yield { line: L('return result;'), event: 'done', state: bitState([['missing', result]]), vars: { result }, note: `XOR cancellation leaves missing value ${result}.`, result }; } };

export const subsetsXor: TraceModule<{ nums: number[] }> = { renderer: 'bit-grid', inputSchema: { nums: { type: 'int-array', label: 'Input values', min: 0, max: 8 } }, defaultInput: { nums: [1, 3] }, samples: [{ input: { nums: [1, 3] }, expected: 6 }, { input: { nums: [5, 1, 6] }, expected: 28 }], run: function* ({ nums }, L) { let totalSum = 0; const limit = 1 << nums.length; for (let mask = 0; mask < limit; mask++) { let xorTotal = 0; for (let i = 0; i < nums.length; i++) if (mask & (1 << i)) xorTotal ^= nums[i]; totalSum += xorTotal; yield { line: L('totalSum += xorTotal;'), event: 'record', state: bitState([['mask', mask], ['xor', xorTotal]]), vars: { mask, xorTotal, totalSum }, note: `Subset mask ${mask} contributes XOR ${xorTotal}.` }; } yield { line: L('return totalSum;'), event: 'done', state: bitState([['total', totalSum]]), vars: { totalSum }, note: `All ${limit} subset XOR totals have been accumulated.`, result: totalSum }; } };

export const sumOfTwoIntegers: TraceModule<{ a: number; b: number }> = { renderer: 'bit-grid', inputSchema: { a: { type: 'int', label: 'First integer' }, b: { type: 'int', label: 'Second integer' } }, defaultInput: { a: 5, b: 7 }, samples: [{ input: { a: 5, b: 7 }, expected: 12 }, { input: { a: -3, b: 1 }, expected: -2 }], run: function* ({ a, b }, L) { let x = a | 0, y = b | 0; while (y !== 0) { const carry = (x & y) << 1; x = (x ^ y) | 0; y = carry | 0; yield { line: L('while (b != 0) {'), event: 'bit-op', state: bitState([['sum', x], ['carry', y]]), vars: { a: x, b: y }, note: 'XOR adds without carry; shifted AND carries the remaining bits.' }; } yield { line: L('return a;'), event: 'done', state: bitState([['sum', x]]), vars: { a: x }, note: `Bitwise addition converged to ${x}.`, result: x }; } };

export const divideIntegers: TraceModule<{ dividend: number; divisor: number }> = { renderer: 'bit-grid', inputSchema: { dividend: { type: 'int', label: 'Dividend' }, divisor: { type: 'int', label: 'Divisor', min: 1 } }, defaultInput: { dividend: 43, divisor: -8 }, samples: [{ input: { dividend: 43, divisor: -8 }, expected: -5 }, { input: { dividend: 10, divisor: 3 }, expected: 3 }], run: function* ({ dividend, divisor }, L) { if (dividend === -2147483648 && divisor === -1) { yield { line: L('if (dividend == INT_MIN && divisor == -1) return INT_MAX;  // overflow guard'), event: 'done', state: bitState([['result', 2147483647]]), vars: {}, note: 'Clamp the only signed division overflow.', result: 2147483647 }; return; } const negative = (dividend < 0) !== (divisor < 0); let dvd = Math.abs(dividend), dvs = Math.abs(divisor), quotient = 0; while (dvd >= dvs) { let temp = dvs, multiple = 1; while (dvd >= temp * 2) { temp *= 2; multiple *= 2; } dvd -= temp; quotient += multiple; yield { line: L('dvd -= temp;                   // subtract the largest fitting chunk'), event: 'bit-op', state: bitState([['remaining', dvd], ['chunk', temp]]), vars: { dvd, temp, multiple, quotient }, note: `Subtract the largest doubled divisor chunk ${temp}.` }; } const result = negative ? -quotient : quotient; yield { line: L('return negative ? -quotient : quotient;'), event: 'done', state: bitState([['quotient', result]]), vars: { quotient: result }, note: `Truncated quotient is ${result}.`, result }; } };

export const rangeAnd: TraceModule<{ left: number; right: number }> = { renderer: 'bit-grid', inputSchema: { left: { type: 'int', label: 'Left', min: 0 }, right: { type: 'int', label: 'Right', min: 0 } }, defaultInput: { left: 5, right: 7 }, samples: [{ input: { left: 5, right: 7 }, expected: 4 }, { input: { left: 0, right: 1 }, expected: 0 }], run: function* ({ left, right }, L) { let shift = 0, l = left, r = right; while (l !== r) { l >>>= 1; r >>>= 1; shift++; yield { line: L('left >>= 1;'), event: 'bit-op', state: bitState([['left', l], ['right', r]]), vars: { left: l, right: r, shift }, note: `Drop one differing low bit; common prefix shift is ${shift}.` }; } const result = l << shift; yield { line: L('return left << shift;'), event: 'done', state: bitState([['result', result]]), vars: { left: l, shift }, note: 'Restore the common prefix and fill dropped bits with zero.', result }; } };

export const numberComplement: TraceModule<{ num: number }> = { renderer: 'bit-grid', inputSchema: { num: { type: 'int', label: 'Positive integer', min: 1, max: 2147483647 } }, defaultInput: { num: 5 }, samples: [{ input: { num: 5 }, expected: 2 }, { input: { num: 1 }, expected: 0 }], run: function* ({ num }, L) { let mask = 1; while (mask < num) { mask = (mask << 1) | 1; yield { line: L('mask = (mask << 1) | 1;'), event: 'bit-op', state: bitState([['num', num], ['mask', mask]]), vars: { num, mask }, note: 'Grow an all-ones mask to the input bit length.' }; } const result = num ^ mask; yield { line: L('return num ^ mask;'), event: 'done', state: bitState([['num', num], ['mask', mask], ['complement', result]]), vars: { num, mask, result }, note: 'XOR flips every bit inside the input bit length.', result }; } };

export const reverseBits: TraceModule<{ n: number }> = { renderer: 'bit-grid', inputSchema: { n: { type: 'int', label: 'Unsigned 32-bit integer', min: 0, max: 4294967295 } }, defaultInput: { n: 43261596 }, samples: [{ input: { n: 43261596 }, expected: 964176192 }, { input: { n: 1 }, expected: 2147483648 }], run: function* ({ n }, L) { let value = n >>> 0, result = 0; for (let i = 0; i < 32; i++) { result = ((result << 1) | (value & 1)) >>> 0; value >>>= 1; yield { line: L('result |= (n & 1);         // append n\'s lowest bit to result'), event: 'bit-op', state: bitState([['result', result], ['remaining', value]], 31 - i), vars: { i, n: value, result }, note: `Move source bit ${i} into destination bit ${31 - i}.` }; } yield { line: L('return result;'), event: 'done', state: bitState([['reversed', result]]), vars: { result }, note: 'All 32 bits have been reversed.', result }; } };

export const maximumXor: TraceModule<{ nums: number[] }> = { renderer: 'bit-grid', inputSchema: { nums: { type: 'int-array', label: 'Non-negative integers', min: 2, max: 12 } }, defaultInput: { nums: [3, 10, 5, 25, 2, 8] }, samples: [{ input: { nums: [3, 10, 5, 25, 2, 8] }, expected: 28 }, { input: { nums: [0, 1, 2, 3, 4], }, expected: 7 }], run: function* ({ nums }, L) { let maxXor = 0; for (const a of nums) for (const b of nums) { const value = a ^ b; if (value > maxXor) maxXor = value; yield { line: L('maxXor = max(maxXor, queryMaxXor(num));'), event: 'bit-op', state: bitState([['num', a], ['candidate', b], ['max', maxXor]]), vars: { a, b, value, maxXor }, note: `Compare XOR ${a} ^ ${b} = ${value}; retain the largest result.` }; } yield { line: L('return maxXor;'), event: 'done', state: bitState([['maximum', maxXor]]), vars: { maxXor }, note: `Maximum pair XOR is ${maxXor}.`, result: maxXor }; } };

export const subsetsBitmask: TraceModule<{ nums: number[] }> = { renderer: 'bit-grid', inputSchema: { nums: { type: 'int-array', label: 'Input values', min: 0, max: 8 } }, defaultInput: { nums: [1, 2, 3] }, samples: [{ input: { nums: [1, 2, 3] }, expected: [[], [1], [2], [1, 2], [3], [1, 3], [2, 3], [1, 2, 3]] }, { input: { nums: [0] }, expected: [[], [0]] }], run: function* ({ nums }, L) { const res: number[][] = []; for (let mask = 0; mask < (1 << nums.length); mask++) { const subset: number[] = []; for (let i = 0; i < nums.length; i++) if (mask & (1 << i)) subset.push(nums[i]); res.push(subset); yield { line: L('res.push_back(subset);'), event: 'record', state: bitState([['mask', mask]]), vars: { mask, subset: JSON.stringify(subset), count: res.length }, note: `Mask ${mask} selects ${subset.length} input values.` }; } yield { line: L('return res;'), event: 'done', state: bitState([['masks', res.length]]), vars: { count: res.length }, note: `Enumerated all ${res.length} subsets.`, result: res }; } };