import type { TraceModule, ArrayPointersState, IntervalTimelineState } from '../lib/types';
import { apState, buildCells } from '../lib/helpers';

type Intervals = { intervals: [number, number][] };
type Strings = { s: string };

const arrayState = (values: Array<number | string>, active?: number, success?: number): ArrayPointersState => {
  const marks: Record<number, 'pointer-a' | 'success'> = {};
  if (active !== undefined) marks[active] = 'pointer-a';
  if (success !== undefined) marks[success] = 'success';
  return apState(buildCells(values, marks), active === undefined ? [] : [{ name: 'i', index: active, variant: 'a' }]);
};

const timeline = (intervals: [number, number][], active = -1, chosen: number[] = [], sweepLine?: number): IntervalTimelineState => ({
  renderer: 'interval-timeline',
  intervals: intervals.map(([start, end], i) => ({ id: `interval-${i}`, start, end, state: chosen.includes(i) ? 'success' : i === active ? 'pointer-a' : 'idle' })),
  sweepLine,
});

export const minimumNumberOfArrows: TraceModule<Intervals> = {
  renderer: 'interval-timeline', inputSchema: { intervals: { type: 'json', label: 'Balloon intervals' } },
  defaultInput: { intervals: [[10, 16], [2, 8], [1, 6], [7, 12]] },
  samples: [{ input: { intervals: [[10, 16], [2, 8], [1, 6], [7, 12]] }, expected: 2 }, { input: { intervals: [[1, 2], [3, 4], [5, 6]] }, expected: 3 }],
  run: function* ({ intervals }, L) {
    if (!intervals.length) { yield { line: L('if (points.empty()) return 0;'), event: 'done', state: timeline([]), vars: { arrows: 0 }, note: 'No balloons need an arrow.', result: 0 }; return; }
    const sorted = [...intervals].sort((a, b) => a[1] - b[1]); let arrows = 1; let arrowPos = sorted[0][1];
    yield { line: L('sort(points.begin(), points.end(), [](const vector<int>& a, const vector<int>& b) {'), event: 'init', state: timeline(sorted, 0, [0], arrowPos), vars: { arrowPos, arrows }, note: 'Shoot at the earliest finishing balloon.' };
    for (let i = 1; i < sorted.length; i++) {
      yield { line: L('if (points[i][0] > arrowPos) {'), event: 'compare', state: timeline(sorted, i, [0], arrowPos), vars: { i, arrowPos, arrows }, note: `Check whether balloon ${i} lies beyond the current arrow.` };
      if (sorted[i][0] > arrowPos) { arrows++; arrowPos = sorted[i][1]; }
      yield { line: L('arrowPos = points[i][1];'), event: 'choose', state: timeline(sorted, i, [i], arrowPos), vars: { i, arrowPos, arrows }, note: sorted[i][0] > arrowPos ? 'Start a new arrow at this balloon end.' : 'Current arrow bursts this overlapping balloon.' };
    }
    yield { line: L('return arrows;'), event: 'done', state: timeline(sorted, -1, [], arrowPos), vars: { arrows }, note: `Minimum arrows: ${arrows}.`, result: arrows };
  },
};

export const meetingsInRoom: TraceModule<{ start: number[]; end: number[] }> = {
  renderer: 'interval-timeline', inputSchema: { start: { type: 'int-array', label: 'Start times' }, end: { type: 'int-array', label: 'End times' } },
  defaultInput: { start: [1, 3, 0, 5, 8, 5], end: [2, 4, 6, 7, 9, 9] },
  samples: [{ input: { start: [1, 3, 0, 5, 8, 5], end: [2, 4, 6, 7, 9, 9] }, expected: 4 }, { input: { start: [10, 12], end: [11, 13] }, expected: 2 }],
  run: function* ({ start, end }, L) {
    const meetings = start.map((s, i) => [s, end[i]] as [number, number]).sort((a, b) => a[1] - b[1]); let count = 0; let lastEnd = -Infinity; const chosen: number[] = [];
    for (let i = 0; i < meetings.length; i++) { yield { line: L('if (meetings[i].second > lastEnd) {'), event: 'compare', state: timeline(meetings, i, chosen, lastEnd), vars: { i, lastEnd, count }, note: `Test meeting [${meetings[i][0]}, ${meetings[i][1]}] against the room end.` }; if (meetings[i][0] > lastEnd) { count++; lastEnd = meetings[i][1]; chosen.push(i); } }
    yield { line: L('return count;'), event: 'done', state: timeline(meetings, -1, chosen, lastEnd), vars: { count, lastEnd }, note: `The room hosts ${count} non-overlapping meetings.`, result: count };
  },
};

export const insertInterval: TraceModule<{ intervals: [number, number][]; newInterval: [number, number] }> = {
  renderer: 'interval-timeline', inputSchema: { intervals: { type: 'json', label: 'Sorted intervals' }, newInterval: { type: 'json', label: 'New interval' } },
  defaultInput: { intervals: [[1, 3], [6, 9]], newInterval: [2, 5] }, samples: [{ input: { intervals: [[1, 3], [6, 9]], newInterval: [2, 5] }, expected: [[1, 5], [6, 9]] }, { input: { intervals: [[1, 2], [3, 5]], newInterval: [6, 7] }, expected: [[1, 2], [3, 5], [6, 7]] }],
  run: function* ({ intervals, newInterval }, L) { const result: [number, number][] = []; let i = 0; let current: [number, number] = [...newInterval]; while (i < intervals.length && intervals[i][1] < current[0]) { result.push(intervals[i]); i++; yield { line: L('result.push_back(intervals[i]);'), event: 'record', state: timeline([...intervals, current], i, [], current[0]), vars: { i }, note: 'Copy intervals that finish before the new one.' }; } while (i < intervals.length && intervals[i][0] <= current[1]) { current = [Math.min(current[0], intervals[i][0]), Math.max(current[1], intervals[i][1])]; i++; yield { line: L('newInterval[1] = max(newInterval[1], intervals[i][1]);'), event: 'record', state: timeline([...result, current, ...intervals.slice(i)], i - 1, [], current[1]), vars: { i, start: current[0], end: current[1] }, note: 'Merge the overlapping interval into the pending range.' }; } result.push(current); while (i < intervals.length) result.push(intervals[i++]); yield { line: L('return result;'), event: 'done', state: timeline(result), vars: { result: JSON.stringify(result) }, note: 'Insert and merge are complete.', result };
  },
};

export const jumpGameII: TraceModule<{ nums: number[] }> = { renderer: 'array-pointers', inputSchema: { nums: { type: 'int-array', label: 'Jump lengths', min: 1, max: 16 } }, defaultInput: { nums: [2, 3, 1, 1, 4] }, samples: [{ input: { nums: [2, 3, 1, 1, 4] }, expected: 2 }, { input: { nums: [2, 3, 0, 1, 4] }, expected: 2 }], run: function* ({ nums }, L) { let jumps = 0, currEnd = 0, farthest = 0; for (let i = 0; i < nums.length - 1; i++) { farthest = Math.max(farthest, i + nums[i]); yield { line: L('farthest = max(farthest, i + nums[i]);'), event: 'compare', state: arrayState(nums, i), vars: { i, jumps, currEnd, farthest }, note: `Index ${i} extends the current jump frontier.` }; if (i === currEnd) { jumps++; currEnd = farthest; yield { line: L('jumps++;'), event: 'choose', state: arrayState(nums, i), vars: { i, jumps, currEnd }, note: 'The current range ends, so commit one jump.' }; } } yield { line: L('return jumps;'), event: 'done', state: arrayState(nums, nums.length - 1, nums.length - 1), vars: { jumps }, note: `Minimum jumps: ${jumps}.`, result: jumps }; } };

export const jumpGame: TraceModule<{ nums: number[] }> = { renderer: 'array-pointers', inputSchema: { nums: { type: 'int-array', label: 'Jump lengths', min: 1, max: 16 } }, defaultInput: { nums: [2, 3, 1, 1, 4] }, samples: [{ input: { nums: [2, 3, 1, 1, 4] }, expected: true }, { input: { nums: [3, 2, 1, 0, 4] }, expected: false }], run: function* ({ nums }, L) { let farthest = 0; for (let i = 0; i < nums.length; i++) { const reachable = i <= farthest; yield { line: L('if (i > farthest) return false;'), event: 'compare', state: arrayState(nums, i), vars: { i, farthest, reachable }, note: reachable ? `Index ${i} is reachable; extend the frontier.` : `Index ${i} lies beyond the reachable frontier.` }; if (!reachable) { yield { line: L('if (i > farthest) return false;'), event: 'done', state: arrayState(nums, i), vars: { i, farthest }, note: 'A gap makes the final index unreachable.', result: false }; return; } farthest = Math.max(farthest, i + nums[i]); } yield { line: L('return true;'), event: 'done', state: arrayState(nums, nums.length - 1, nums.length - 1), vars: { farthest }, note: 'The scan reaches the final index.', result: true }; } };

export const gasStation: TraceModule<{ gas: number[]; cost: number[] }> = { renderer: 'array-pointers', inputSchema: { gas: { type: 'int-array', label: 'Gas' }, cost: { type: 'int-array', label: 'Cost' } }, defaultInput: { gas: [1, 2, 3, 4, 5], cost: [3, 4, 5, 1, 2] }, samples: [{ input: { gas: [1, 2, 3, 4, 5], cost: [3, 4, 5, 1, 2] }, expected: 3 }, { input: { gas: [2, 3, 4], cost: [3, 4, 3] }, expected: -1 }], run: function* ({ gas, cost }, L) { let totalTank = 0, currTank = 0, start = 0; for (let i = 0; i < gas.length; i++) { const diff = gas[i] - cost[i]; totalTank += diff; currTank += diff; yield { line: L('currTank += diff;'), event: 'calc', state: arrayState(gas.map((v, j) => `${v}/${cost[j]}`), i), vars: { i, diff, currTank, totalTank, start }, note: `Station ${i} changes the tank by ${diff}.` }; if (currTank < 0) { start = i + 1; currTank = 0; yield { line: L('start = i + 1;'), event: 'move-pointer', state: arrayState(gas.map((v, j) => `${v}/${cost[j]}`), start < gas.length ? start : i), vars: { start, currTank }, note: 'A negative tank eliminates every start through this station.' }; } } const result = totalTank >= 0 ? start : -1; yield { line: L('return totalTank >= 0 ? start : -1;'), event: 'done', state: arrayState(gas.map((v, j) => `${v}/${cost[j]}`), result >= 0 ? result : undefined, result >= 0 ? result : undefined), vars: { totalTank, start, result }, note: `Circuit result: ${result}.`, result }; } };

export const assignCookies: TraceModule<{ g: number[]; s: number[] }> = { renderer: 'array-pointers', inputSchema: { g: { type: 'int-array', label: 'Greed factors' }, s: { type: 'int-array', label: 'Cookie sizes' } }, defaultInput: { g: [1, 2, 3], s: [1, 1] }, samples: [{ input: { g: [1, 2, 3], s: [1, 1] }, expected: 1 }, { input: { g: [1, 2], s: [1, 2, 3] }, expected: 2 }], run: function* ({ g, s }, L) { const children = [...g].sort((a, b) => a - b), cookies = [...s].sort((a, b) => a - b); let child = 0, cookie = 0; while (child < children.length && cookie < cookies.length) { const fits = cookies[cookie] >= children[child]; yield { line: L('if (s[cookie] >= g[child]) {'), event: 'compare', state: arrayState(children.map(String).concat('|', cookies.map(String)), child), vars: { child, cookie, fits }, note: `Try cookie ${cookies[cookie]} for child greed ${children[child]}.` }; if (fits) child++; cookie++; } yield { line: L('return child;'), event: 'done', state: arrayState(children, child ? child - 1 : undefined, child ? child - 1 : undefined), vars: { child }, note: `${child} children receive a sufficient cookie.`, result: child }; } };

export const boatsToSavePeople: TraceModule<{ people: number[]; limit: number }> = { renderer: 'array-pointers', inputSchema: { people: { type: 'int-array', label: 'Weights' }, limit: { type: 'int', label: 'Boat limit', min: 1 } }, defaultInput: { people: [3, 2, 2, 1], limit: 3 }, samples: [{ input: { people: [3, 2, 2, 1], limit: 3 }, expected: 3 }, { input: { people: [1, 2], limit: 3 }, expected: 1 }], run: function* ({ people, limit }, L) { const values = [...people].sort((a, b) => a - b); let lo = 0, hi = values.length - 1, boats = 0; while (lo <= hi) { const pair = values[lo] + values[hi] <= limit; yield { line: L('if (people[lo] + people[hi] <= limit) {'), event: 'compare', state: arrayState(values, hi), vars: { lo, hi, boats, pair }, note: pair ? 'Lightest and heaviest can share one boat.' : 'The heaviest person must ride alone.' }; if (pair) lo++; hi--; boats++; } yield { line: L('return boats;'), event: 'done', state: arrayState(values), vars: { boats }, note: `Minimum boats: ${boats}.`, result: boats }; } };

export const twoCityScheduling: TraceModule<{ costs: [number, number][] }> = { renderer: 'array-pointers', inputSchema: { costs: { type: 'json', label: 'City A/B costs' } }, defaultInput: { costs: [[10, 20], [30, 200], [400, 50], [30, 20]] }, samples: [{ input: { costs: [[10, 20], [30, 200], [400, 50], [30, 20]] }, expected: 110 }, { input: { costs: [[10, 1], [2, 3], [5, 6], [7, 8]] }, expected: 16 }], run: function* ({ costs }, L) { const sorted = [...costs].sort((a, b) => a[0] - a[1] - (b[0] - b[1])); const half = sorted.length / 2; let total = 0; for (let i = 0; i < sorted.length; i++) { total += i < half ? sorted[i][0] : sorted[i][1]; yield { line: L('total += (i < n) ? costs[i][0] : costs[i][1];'), event: 'choose', state: arrayState(sorted.map(([a, b]) => `${a}/${b}`), i), vars: { i, total, city: i < half ? 'A' : 'B' }, note: `Assign person ${i} to the cheaper relative destination.` }; } yield { line: L('return total;'), event: 'done', state: arrayState(sorted.map(([a, b]) => `${a}/${b}`)), vars: { total }, note: `Minimum travel cost: ${total}.`, result: total }; } };

export const removeDuplicateLetters: TraceModule<Strings> = { renderer: 'array-pointers', inputSchema: { s: { type: 'string', label: 'Lowercase string' } }, defaultInput: { s: 'cbacdcbc' }, samples: [{ input: { s: 'bcabc' }, expected: 'abc' }, { input: { s: 'cbacdcbc' }, expected: 'acdb' }], run: function* ({ s }, L) { const last = new Map<string, number>(); [...s].forEach((c, i) => last.set(c, i)); const stack: string[] = []; const inStack = new Set<string>(); for (let i = 0; i < s.length; i++) { const c = s[i]; if (inStack.has(c)) continue; while (stack.length && stack[stack.length - 1] > c && (last.get(stack[stack.length - 1]) ?? -1) > i) { inStack.delete(stack.pop()!); yield { line: L('stk.pop_back();'), event: 'shrink', state: arrayState(stack, i), vars: { i, stack: stack.join('') }, note: `Pop a larger character that appears again later.` }; } stack.push(c); inStack.add(c); yield { line: L('stk.push_back(c);'), event: 'record', state: arrayState([...s], i), vars: { i, stack: stack.join('') }, note: `Keep ${c} as the smallest safe next character.` }; } const result = stack.join(''); yield { line: L('return stk;'), event: 'done', state: arrayState([...result], undefined), vars: { result }, note: `Smallest distinct subsequence: ${result}.`, result }; } };

export const candy: TraceModule<{ ratings: number[] }> = { renderer: 'array-pointers', inputSchema: { ratings: { type: 'int-array', label: 'Ratings' } }, defaultInput: { ratings: [1, 0, 2] }, samples: [{ input: { ratings: [1, 0, 2] }, expected: 5 }, { input: { ratings: [1, 2, 2] }, expected: 4 }], run: function* ({ ratings }, L) { const candies = Array(ratings.length).fill(1); for (let i = 1; i < ratings.length; i++) { if (ratings[i] > ratings[i - 1]) candies[i] = candies[i - 1] + 1; yield { line: L('candies[i] = candies[i - 1] + 1;'), event: 'write', state: arrayState(candies, i), vars: { i, candies: JSON.stringify(candies) }, note: 'Enforce the higher-than-left-neighbor rule.' }; } for (let i = ratings.length - 2; i >= 0; i--) { if (ratings[i] > ratings[i + 1]) candies[i] = Math.max(candies[i], candies[i + 1] + 1); yield { line: L('candies[i] = max(candies[i], candies[i + 1] + 1);'), event: 'write', state: arrayState(candies, i), vars: { i, candies: JSON.stringify(candies) }, note: 'Enforce the right-neighbor rule without losing the first pass.' }; } const result = candies.reduce((a, b) => a + b, 0); yield { line: L('for (int c : candies) total += c;'), event: 'done', state: arrayState(candies), vars: { candies: JSON.stringify(candies), result }, note: `Minimum candies: ${result}.`, result }; } };

export const partitionLabels: TraceModule<Strings> = { renderer: 'array-pointers', inputSchema: { s: { type: 'string', label: 'Lowercase string' } }, defaultInput: { s: 'ababcbacadefegdehijhklij' }, samples: [{ input: { s: 'ababcbacadefegdehijhklij' }, expected: [9, 7, 8] }, { input: { s: 'eccbbbbdec' }, expected: [10] }], run: function* ({ s }, L) { const last = new Map<string, number>(); [...s].forEach((c, i) => last.set(c, i)); const result: number[] = []; let start = 0, end = 0; for (let i = 0; i < s.length; i++) { end = Math.max(end, last.get(s[i])!); yield { line: L('end = max(end, lastIndex[s[i] - \'a\']);'), event: 'expand', state: arrayState([...s], i), vars: { i, start, end }, note: `Extend the partition to ${end}, the last occurrence of ${s[i]}.` }; if (i === end) { result.push(end - start + 1); start = i + 1; yield { line: L('result.push_back(end - start + 1);'), event: 'record', state: arrayState([...s], i, i), vars: { start, end, result: JSON.stringify(result) }, note: 'Every character in this partition is now complete.' }; } } yield { line: L('return result;'), event: 'done', state: arrayState([...s]), vars: { result: JSON.stringify(result) }, note: `Partition sizes: ${result.join(', ')}.`, result }; } };

export const taskScheduler: TraceModule<{ tasks: string[]; n: number }> = { renderer: 'array-pointers', inputSchema: { tasks: { type: 'string', label: 'Tasks' }, n: { type: 'int', label: 'Cooldown', min: 0, max: 10 } }, defaultInput: { tasks: ['A', 'A', 'A', 'B', 'B', 'B'], n: 2 }, samples: [{ input: { tasks: ['A', 'A', 'A', 'B', 'B', 'B'], n: 2 }, expected: 8 }, { input: { tasks: ['A', 'A', 'A', 'B', 'B', 'B'], n: 0 }, expected: 6 }], run: function* ({ tasks, n }, L) { const freq = new Map<string, number>(); for (const task of tasks) freq.set(task, (freq.get(task) ?? 0) + 1); const maxFreq = Math.max(...freq.values()); const maxCount = [...freq.values()].filter(v => v === maxFreq).length; const slots = (maxFreq - 1) * (n + 1) + maxCount; const result = Math.max(tasks.length, slots); yield { line: L('int slots = (maxFreq - 1) * (n + 1) + maxCount;'), event: 'calc', state: arrayState(tasks), vars: { maxFreq, maxCount, slots }, note: 'Build the idle-slot skeleton from the most frequent tasks.' }; yield { line: L('return max((int)tasks.size(), slots);'), event: 'done', state: arrayState(tasks), vars: { result }, note: `Minimum schedule length: ${result}.`, result }; } };

export const nonOverlappingIntervals: TraceModule<Intervals> = { renderer: 'interval-timeline', inputSchema: { intervals: { type: 'json', label: 'Intervals' } }, defaultInput: { intervals: [[1, 2], [2, 3], [3, 4], [1, 3]] }, samples: [{ input: { intervals: [[1, 2], [2, 3], [3, 4], [1, 3]] }, expected: 1 }, { input: { intervals: [[1, 2], [1, 2], [1, 2] ] }, expected: 2 }], run: function* ({ intervals }, L) { const sorted = [...intervals].sort((a, b) => a[1] - b[1]); let removed = 0, prevEnd = -Infinity; const kept: number[] = []; for (let i = 0; i < sorted.length; i++) { const overlap = sorted[i][0] < prevEnd; yield { line: L('if (intervals[i][0] < prevEnd) {'), event: 'compare', state: timeline(sorted, i, kept, prevEnd), vars: { i, prevEnd, removed, overlap }, note: overlap ? 'Overlap: remove this interval and keep the earlier ending one.' : 'Keep this interval; it leaves the earliest possible end.' }; if (overlap) removed++; else { prevEnd = sorted[i][1]; kept.push(i); } } yield { line: L('return count;'), event: 'done', state: timeline(sorted, -1, kept, prevEnd), vars: { removed }, note: `Remove ${removed} interval(s) to eliminate overlaps.`, result: removed }; } };

export const removeKDigits: TraceModule<{ num: string; k: number }> = { renderer: 'array-pointers', inputSchema: { num: { type: 'string', label: 'Number string' }, k: { type: 'int', label: 'Digits to remove', min: 0 } }, defaultInput: { num: '1432219', k: 3 }, samples: [{ input: { num: '1432219', k: 3 }, expected: '1219' }, { input: { num: '10200', k: 1 }, expected: '200' }], run: function* ({ num, k }, L) { const stack: string[] = []; let remaining = k; for (const digit of num) { while (stack.length && remaining > 0 && stack.at(-1)! > digit) { stack.pop(); remaining--; yield { line: L('stk.pop_back();'), event: 'shrink', state: arrayState([...num], undefined), vars: { digit, remaining, stack: stack.join('') }, note: `Remove a larger leading digit before ${digit}.` }; } stack.push(digit); yield { line: L('stk.push_back(c);'), event: 'record', state: arrayState([...num]), vars: { digit, remaining, stack: stack.join('') }, note: `Push ${digit} while preserving an increasing prefix.` }; } while (remaining-- > 0) stack.pop(); const result = (stack.join('').replace(/^0+(?=\d)/, '') || '0'); yield { line: L('return stk.empty() ? "0" : stk;'), event: 'done', state: arrayState([...result]), vars: { result }, note: `Smallest number after removals: ${result}.`, result }; } };

export const ipo: TraceModule<{ k: number; w: number; profits: number[]; capital: number[] }> = { renderer: 'array-pointers', inputSchema: { k: { type: 'int', label: 'Projects to choose', min: 0 }, w: { type: 'int', label: 'Starting capital', min: 0 }, profits: { type: 'int-array', label: 'Profits' }, capital: { type: 'int-array', label: 'Required capital' } }, defaultInput: { k: 2, w: 0, profits: [1, 2, 3], capital: [0, 1, 1] }, samples: [{ input: { k: 2, w: 0, profits: [1, 2, 3], capital: [0, 1, 1] }, expected: 4 }, { input: { k: 3, w: 0, profits: [1, 2, 3], capital: [0, 1, 2] }, expected: 6 }], run: function* ({ k, w, profits, capital }, L) { const projects = profits.map((profit, i) => ({ profit, capital: capital[i] })).sort((a, b) => a.capital - b.capital); const available: number[] = []; let index = 0; for (let step = 0; step < k; step++) { while (index < projects.length && projects[index].capital <= w) available.push(projects[index++].profit); if (!available.length) break; available.sort((a, b) => b - a); const profit = available.shift()!; w += profit; yield { line: L('w += maxHeap.top();'), event: 'choose', state: arrayState(projects.map(project => `${project.capital}/${project.profit}`)), vars: { step, profit, w, available: available.join(',') }, note: `Fund the most profitable project currently affordable.` }; } yield { line: L('return w;'), event: 'done', state: arrayState(projects.map(project => `${project.capital}/${project.profit}`)), vars: { w }, note: `Final capital: ${w}.`, result: w }; } };

export const reorganizeString: TraceModule<{ s: string }> = { renderer: 'array-pointers', inputSchema: { s: { type: 'string', label: 'Lowercase string' } }, defaultInput: { s: 'aab' }, samples: [{ input: { s: 'aab' }, expected: 'aba' }, { input: { s: 'aaab' }, expected: '' }], run: function* ({ s }, L) { const counts = new Map<string, number>(); for (const c of s) counts.set(c, (counts.get(c) ?? 0) + 1); let result = ''; let previous = ''; for (let i = 0; i < s.length; i++) { const choices = [...counts.entries()].filter(([c, count]) => count > 0 && c !== previous).sort((a, b) => b[1] - a[1]); if (!choices.length) { yield { line: L('if (maxFreq > (int)(s.size() + 1) / 2) return "";'), event: 'done', state: arrayState([...result]), vars: { result: '' }, note: 'No distinct character is available for the next position.', result: '' }; return; } const [character, count] = choices[0]; result += character; counts.set(character, count - 1); previous = character; yield { line: L('result += c1;'), event: 'choose', state: arrayState([...result]), vars: { i, result }, note: `Place ${character}, then reserve a different character next.` }; } yield { line: L('return result;'), event: 'done', state: arrayState([...result]), vars: { result }, note: `Reorganized string: ${result}.`, result }; } };
