import type { TraceModule, DPTableState } from '../lib/types';

const tableState = (values: number[][], active?: [number, number]): DPTableState => ({ renderer: 'dp-table', table: values.map((row, r) => row.map((value, c) => ({ value, state: active && active[0] === r && active[1] === c ? 'pointer-a' : value === 0 ? 'idle' : 'visited' }))), pointers: active ? [{ r: active[0], c: active[1], variant: 'a', name: 'cell' }] : undefined });
const rowState = (values: number[], active?: number): DPTableState => tableState([values], active === undefined ? undefined : [0, active]);

export const houseRobber: TraceModule<{ nums: number[] }> = { renderer: 'dp-table', inputSchema: { nums: { type: 'int-array', label: 'House values', min: 0, max: 16 } }, defaultInput: { nums: [2, 7, 9, 3, 1] }, samples: [{ input: { nums: [2, 7, 9, 3, 1] }, expected: 12 }, { input: { nums: [2, 1, 1, 2] }, expected: 4 }], run: function* ({ nums }, L) { const dp: number[] = []; for (let i = 0; i < nums.length; i++) { dp[i] = Math.max(dp[i - 1] ?? 0, (dp[i - 2] ?? 0) + nums[i]); yield { line: L('int cur = max(prev1, prev2 + num);'), event: 'calc', state: rowState(dp, i), vars: { i, num: nums[i], cur: dp[i], dp: JSON.stringify(dp) }, note: `At house ${i}, choose rob ${nums[i]} or skip it.` }; } const result = dp.at(-1) ?? 0; yield { line: L('return prev1;'), event: 'done', state: rowState(dp), vars: { result }, note: `Maximum loot: ${result}.`, result }; } };

export const houseRobberII: TraceModule<{ nums: number[] }> = { renderer: 'dp-table', inputSchema: { nums: { type: 'int-array', label: 'Circular house values', min: 1, max: 16 } }, defaultInput: { nums: [2, 3, 2] }, samples: [{ input: { nums: [2, 3, 2] }, expected: 3 }, { input: { nums: [1, 2, 3, 1] }, expected: 4 }], run: function* ({ nums }, L) { const solve = (values: number[]) => { let a = 0, b = 0; for (const value of values) [a, b] = [b, Math.max(b, a + value)]; return b; }; const withoutLast = solve(nums.slice(0, -1)), withoutFirst = solve(nums.slice(1)); yield { line: L('return max(robLine(nums, 0, n - 2), robLine(nums, 1, n - 1));'), event: 'compare', state: rowState([withoutLast, withoutFirst]), vars: { withoutLast, withoutFirst }, note: 'Compare the two legal cases: exclude the last or the first house.' }; const result = Math.max(withoutLast, withoutFirst); yield { line: L('return max(robLine(nums, 0, n - 2), robLine(nums, 1, n - 1));'), event: 'done', state: rowState([result]), vars: { result }, note: `Maximum circular loot: ${result}.`, result }; } };

export const decodeWays: TraceModule<{ s: string }> = { renderer: 'dp-table', inputSchema: { s: { type: 'string', label: 'Digit string' } }, defaultInput: { s: '226' }, samples: [{ input: { s: '12' }, expected: 2 }, { input: { s: '226' }, expected: 3 }], run: function* ({ s }, L) { const dp = Array(s.length + 1).fill(0); dp[0] = 1; if (s[0] !== '0') dp[1] = 1; for (let i = 2; i <= s.length; i++) { const one = Number(s[i - 1]), two = Number(s.slice(i - 2, i)); if (one >= 1) dp[i] += dp[i - 1]; if (two >= 10 && two <= 26) dp[i] += dp[i - 2]; yield { line: L('int cur = 0;'), event: 'calc', state: rowState(dp, i), vars: { i, oneDigit: one, twoDigit: two, cur: dp[i] }, note: `Prefix ${s.slice(0, i)} has ${dp[i]} valid decodings.` }; } const result = dp[s.length]; yield { line: L('return prev1;'), event: 'done', state: rowState(dp), vars: { result }, note: `Decoding count: ${result}.`, result }; } };

export const uniquePaths: TraceModule<{ m: number; n: number }> = { renderer: 'dp-table', inputSchema: { m: { type: 'int', label: 'Rows', min: 1, max: 8 }, n: { type: 'int', label: 'Columns', min: 1, max: 8 } }, defaultInput: { m: 3, n: 7 }, samples: [{ input: { m: 3, n: 7 }, expected: 28 }, { input: { m: 3, n: 2 }, expected: 3 }], run: function* ({ m, n }, L) { const dp = Array(m).fill(0).map(() => Array(n).fill(1)); for (let r = 1; r < m; r++) for (let c = 1; c < n; c++) { dp[r][c] = dp[r - 1][c] + dp[r][c - 1]; yield { line: L('dp[j] += dp[j - 1];'), event: 'fill-cell', state: tableState(dp, [r, c]), vars: { r, c, value: dp[r][c] }, note: 'Add paths arriving from above and from the left.' }; } const result = dp[m - 1][n - 1]; yield { line: L('return dp[n - 1];'), event: 'done', state: tableState(dp), vars: { result }, note: `There are ${result} paths.`, result }; } };

export const uniquePathsII: TraceModule<{ grid: number[][] }> = { renderer: 'dp-table', inputSchema: { grid: { type: 'int-grid', label: 'Obstacle grid', min: 1, max: 8 } }, defaultInput: { grid: [[0, 0, 0], [0, 1, 0], [0, 0, 0]] }, samples: [{ input: { grid: [[0, 0, 0], [0, 1, 0], [0, 0, 0]] }, expected: 2 }, { input: { grid: [[1, 0]], }, expected: 0 }], run: function* ({ grid }, L) { const m = grid.length, n = grid[0].length, dp = Array(m).fill(0).map(() => Array(n).fill(0)); for (let r = 0; r < m; r++) for (let c = 0; c < n; c++) { if (!grid[r][c]) dp[r][c] = r === 0 && c === 0 ? 1 : (dp[r - 1]?.[c] ?? 0) + (dp[r]?.[c - 1] ?? 0); yield { line: L('if (grid[i][j] == 1) {'), event: 'fill-cell', state: tableState(dp, [r, c]), vars: { r, c, obstacle: grid[r][c], value: dp[r][c] }, note: grid[r][c] ? 'Obstacle blocks every path through this cell.' : 'Accumulate paths from the top and left.' }; } const result = dp[m - 1][n - 1]; yield { line: L('return (int)dp[n - 1];'), event: 'done', state: tableState(dp), vars: { result }, note: `Reachable paths: ${result}.`, result }; } };

export const minimumPathSum: TraceModule<{ grid: number[][] }> = { renderer: 'dp-table', inputSchema: { grid: { type: 'int-grid', label: 'Cost grid', min: 1, max: 8 } }, defaultInput: { grid: [[1, 3, 1], [1, 5, 1], [4, 2, 1]] }, samples: [{ input: { grid: [[1, 3, 1], [1, 5, 1], [4, 2, 1]] }, expected: 7 }, { input: { grid: [[1, 2], [1, 1]] }, expected: 3 }], run: function* ({ grid }, L) { const dp = Array(grid[0].length).fill(Infinity); dp[0] = 0; for (let r = 0; r < grid.length; r++) for (let c = 0; c < grid[0].length; c++) { dp[c] = grid[r][c] + Math.min(dp[c], c ? dp[c - 1] : Infinity); yield { line: L('dp[j] = grid[i][j] + min(dp[j], dp[j - 1]);'), event: 'fill-cell', state: rowState(dp, c), vars: { r, c, value: dp[c] }, note: `Best cost to cell (${r}, ${c}) is ${dp[c]}.` }; } const result = dp.at(-1)!; yield { line: L('return dp[n - 1];'), event: 'done', state: rowState(dp), vars: { result }, note: `Minimum path sum: ${result}.`, result }; } };

export const partitionEqualSubsetSum: TraceModule<{ nums: number[] }> = { renderer: 'dp-table', inputSchema: { nums: { type: 'int-array', label: 'Positive values', min: 1, max: 16 } }, defaultInput: { nums: [1, 5, 11, 5] }, samples: [{ input: { nums: [1, 5, 11, 5] }, expected: true }, { input: { nums: [1, 2, 3, 5] }, expected: false }], run: function* ({ nums }, L) { const total = nums.reduce((a, b) => a + b, 0); if (total % 2) { yield { line: L('if (total % 2 != 0) return false;'), event: 'done', state: rowState([0]), vars: { total }, note: 'An odd total cannot split into equal integer sums.', result: false }; return; } const target = total / 2, dp = Array(target + 1).fill(0); dp[0] = 1; for (const num of nums) for (let s = target; s >= num; s--) dp[s] ||= dp[s - num]; const result = Boolean(dp[target]); yield { line: L('return dp[target];'), event: 'done', state: rowState(dp), vars: { target, result }, note: `Target sum ${target} is ${result ? '' : 'not '}reachable.`, result }; } };

export const targetSum: TraceModule<{ nums: number[]; target: number }> = { renderer: 'dp-table', inputSchema: { nums: { type: 'int-array', label: 'Numbers' }, target: { type: 'int', label: 'Target' } }, defaultInput: { nums: [1, 1, 1, 1, 1], target: 3 }, samples: [{ input: { nums: [1, 1, 1, 1, 1], target: 3 }, expected: 5 }, { input: { nums: [1], target: 2 }, expected: 0 }], run: function* ({ nums, target }, L) { const total = nums.reduce((a, b) => a + b, 0); const p = total + target; if (Math.abs(target) > total || p % 2) { yield { line: L('if (abs(target) > total || (total + target) % 2 != 0) return 0;'), event: 'done', state: rowState([0]), vars: { total, target }, note: 'No subset transformation can reach this target.', result: 0 }; return; } const sum = p / 2, dp = Array(sum + 1).fill(0); dp[0] = 1; for (const num of nums) for (let s = sum; s >= num; s--) dp[s] += dp[s - num]; const result = dp[sum]; yield { line: L('return dp[P];'), event: 'done', state: rowState(dp), vars: { P: sum, result }, note: `${result} sign assignments reach ${target}.`, result }; } };

export const coinChange: TraceModule<{ coins: number[]; amount: number }> = { renderer: 'dp-table', inputSchema: { coins: { type: 'int-array', label: 'Coin denominations' }, amount: { type: 'int', label: 'Amount', min: 0, max: 64 } }, defaultInput: { coins: [1, 2, 5], amount: 11 }, samples: [{ input: { coins: [1, 2, 5], amount: 11 }, expected: 3 }, { input: { coins: [2], amount: 3 }, expected: -1 }], run: function* ({ coins, amount }, L) { const dp = Array(amount + 1).fill(Infinity); dp[0] = 0; for (let a = 1; a <= amount; a++) { for (const coin of coins) if (coin <= a) dp[a] = Math.min(dp[a], dp[a - coin] + 1); yield { line: L('dp[a] = min(dp[a], dp[a - coin] + 1);'), event: 'fill-cell', state: rowState(dp.map(v => Number.isFinite(v) ? v : -1), a), vars: { a, value: dp[a] }, note: `Best way to make ${a} uses ${Number.isFinite(dp[a]) ? dp[a] : 'no'} coins.` }; } const result = Number.isFinite(dp[amount]) ? dp[amount] : -1; yield { line: L('return dp[amount] == INT_MAX ? -1 : dp[amount];'), event: 'done', state: rowState(dp.map(v => Number.isFinite(v) ? v : -1)), vars: { result }, note: `Fewest coins: ${result}.`, result }; } };

export const coinChangeII: TraceModule<{ amount: number; coins: number[] }> = { renderer: 'dp-table', inputSchema: { amount: { type: 'int', label: 'Amount', min: 0, max: 64 }, coins: { type: 'int-array', label: 'Coin denominations' } }, defaultInput: { amount: 5, coins: [1, 2, 5] }, samples: [{ input: { amount: 5, coins: [1, 2, 5] }, expected: 4 }, { input: { amount: 3, coins: [2] }, expected: 0 }], run: function* ({ amount, coins }, L) { const dp = Array(amount + 1).fill(0); dp[0] = 1; for (const coin of coins) { for (let a = coin; a <= amount; a++) dp[a] += dp[a - coin]; yield { line: L('dp[a] += dp[a - coin];'), event: 'fill-cell', state: rowState(dp), vars: { coin, ways: dp[amount] }, note: `Allow coin ${coin}; combinations remain order-independent.` }; } const result = dp[amount]; yield { line: L('return dp[amount];'), event: 'done', state: rowState(dp), vars: { result }, note: `Distinct combinations: ${result}.`, result }; } };

export const longestCommonSubsequence: TraceModule<{ text1: string; text2: string }> = { renderer: 'dp-table', inputSchema: { text1: { type: 'string', label: 'First string' }, text2: { type: 'string', label: 'Second string' } }, defaultInput: { text1: 'abcde', text2: 'ace' }, samples: [{ input: { text1: 'abcde', text2: 'ace' }, expected: 3 }, { input: { text1: 'abc', text2: 'abc' }, expected: 3 }], run: function* ({ text1, text2 }, L) { const dp = Array(text1.length + 1).fill(0).map(() => Array(text2.length + 1).fill(0)); for (let i = 1; i <= text1.length; i++) for (let j = 1; j <= text2.length; j++) { dp[i][j] = text1[i - 1] === text2[j - 1] ? dp[i - 1][j - 1] + 1 : Math.max(dp[i - 1][j], dp[i][j - 1]); yield { line: L('dp[i][j] = max(dp[i - 1][j], dp[i][j - 1]);'), event: 'fill-cell', state: tableState(dp, [i, j]), vars: { i, j, value: dp[i][j] }, note: text1[i - 1] === text2[j - 1] ? 'Matching characters extend the diagonal subsequence.' : 'Keep the better subsequence after dropping one character.' }; } const result = dp[text1.length][text2.length]; yield { line: L('return dp[m][n];'), event: 'done', state: tableState(dp), vars: { result }, note: `LCS length: ${result}.`, result }; } };

export const editDistance: TraceModule<{ word1: string; word2: string }> = { renderer: 'dp-table', inputSchema: { word1: { type: 'string', label: 'Source word' }, word2: { type: 'string', label: 'Target word' } }, defaultInput: { word1: 'horse', word2: 'ros' }, samples: [{ input: { word1: 'horse', word2: 'ros' }, expected: 3 }, { input: { word1: 'intention', word2: 'execution' }, expected: 5 }], run: function* ({ word1, word2 }, L) { const dp = Array(word1.length + 1).fill(0).map((_, i) => Array.from({ length: word2.length + 1 }, (_, j) => i === 0 ? j : j === 0 ? i : 0)); for (let i = 1; i <= word1.length; i++) for (let j = 1; j <= word2.length; j++) { dp[i][j] = word1[i - 1] === word2[j - 1] ? dp[i - 1][j - 1] : 1 + Math.min(dp[i - 1][j - 1], dp[i - 1][j], dp[i][j - 1]); yield { line: L('dp[i][j] = 1 + min({dp[i - 1][j - 1],'), event: 'fill-cell', state: tableState(dp, [i, j]), vars: { i, j, value: dp[i][j] }, note: word1[i - 1] === word2[j - 1] ? 'Matching characters need no operation.' : 'Choose the cheapest replace, delete, or insert operation.' }; } const result = dp[word1.length][word2.length]; yield { line: L('return dp[m][n];'), event: 'done', state: tableState(dp), vars: { result }, note: `Edit distance: ${result}.`, result }; } };

export const longestIncreasingSubsequence: TraceModule<{ nums: number[] }> = { renderer: 'dp-table', inputSchema: { nums: { type: 'int-array', label: 'Sequence' } }, defaultInput: { nums: [10, 9, 2, 5, 3, 7, 101, 18] }, samples: [{ input: { nums: [10, 9, 2, 5, 3, 7, 101, 18] }, expected: 4 }, { input: { nums: [0, 1, 0, 3, 2, 3] }, expected: 4 }], run: function* ({ nums }, L) { const dp = Array(nums.length).fill(1); for (let i = 0; i < nums.length; i++) { for (let j = 0; j < i; j++) if (nums[j] < nums[i]) dp[i] = Math.max(dp[i], dp[j] + 1); yield { line: L('else *it = num;                               // keeps tail as small as possible'), event: 'calc', state: rowState(dp, i), vars: { i, value: nums[i], length: dp[i] }, note: `Best increasing subsequence ending at ${nums[i]} has length ${dp[i]}.` }; } const result = Math.max(...dp); yield { line: L('return tails.size();'), event: 'done', state: rowState(dp), vars: { result }, note: `Longest increasing subsequence length: ${result}.`, result }; } };

export const longestPalindromicSubstring: TraceModule<{ s: string }> = { renderer: 'dp-table', inputSchema: { s: { type: 'string', label: 'String' } }, defaultInput: { s: 'babad' }, samples: [{ input: { s: 'babad' }, expected: 'bab' }, { input: { s: 'cbbd' }, expected: 'bb' }], run: function* ({ s }, L) { const n = s.length, dp = Array(n).fill(0).map(() => Array(n).fill(0)); let start = 0, maxLen = 0; for (let len = 1; len <= n; len++) for (let i = 0; i + len <= n; i++) { const j = i + len - 1; dp[i][j] = s[i] === s[j] && (len <= 2 || dp[i + 1][j - 1]) ? 1 : 0; if (dp[i][j] && len > maxLen) { start = i; maxLen = len; } yield { line: L('dp[i][j] = true;'), event: 'fill-cell', state: tableState(dp, [i, j]), vars: { i, j, len, palindrome: Boolean(dp[i][j]) }, note: `Check substring ${s.slice(i, j + 1)}.` }; } const result = s.slice(start, start + maxLen); yield { line: L('return s.substr(start, maxLen);'), event: 'done', state: tableState(dp), vars: { start, maxLen }, note: `Longest palindrome: ${result}.`, result }; } };

export const palindromicSubstrings: TraceModule<{ s: string }> = { renderer: 'dp-table', inputSchema: { s: { type: 'string', label: 'String' } }, defaultInput: { s: 'aaa' }, samples: [{ input: { s: 'abc' }, expected: 3 }, { input: { s: 'aaa' }, expected: 6 }], run: function* ({ s }, L) { const n = s.length, dp = Array(n).fill(0).map(() => Array(n).fill(0)); let count = 0; for (let len = 1; len <= n; len++) for (let i = 0; i + len <= n; i++) { const j = i + len - 1; dp[i][j] = s[i] === s[j] && (len <= 2 || dp[i + 1][j - 1]) ? 1 : 0; count += dp[i][j]; yield { line: L('dp[i][j] = true;'), event: 'fill-cell', state: tableState(dp, [i, j]), vars: { i, j, count }, note: dp[i][j] ? 'This substring is palindromic; count it.' : 'Endpoints or inner range break the palindrome.' }; } yield { line: L('return count;'), event: 'done', state: tableState(dp), vars: { count }, note: `Total palindromic substrings: ${count}.`, result: count }; } };

export const longestPalindromicSubsequence: TraceModule<{ s: string }> = { renderer: 'dp-table', inputSchema: { s: { type: 'string', label: 'String' } }, defaultInput: { s: 'bbbab' }, samples: [{ input: { s: 'bbbab' }, expected: 4 }, { input: { s: 'cbbd' }, expected: 2 }], run: function* ({ s }, L) { const n = s.length, dp = Array(n).fill(0).map(() => Array(n).fill(0)); for (let i = n - 1; i >= 0; i--) { dp[i][i] = 1; for (let j = i + 1; j < n; j++) { dp[i][j] = s[i] === s[j] ? (dp[i + 1]?.[j - 1] ?? 0) + 2 : Math.max(dp[i + 1][j], dp[i][j - 1]); yield { line: L('if (s[i] == s[j]) dp[i][j] = dp[i + 1][j - 1] + 2;'), event: 'fill-cell', state: tableState(dp, [i, j]), vars: { i, j, value: dp[i][j] }, note: `Use matching ends or drop the weaker end.` }; } } const result = dp[0][n - 1]; yield { line: L('return dp[0][n - 1];'), event: 'done', state: tableState(dp), vars: { result }, note: `Longest palindromic subsequence: ${result}.`, result }; } };

export const burstBalloons: TraceModule<{ nums: number[] }> = { renderer: 'dp-table', inputSchema: { nums: { type: 'int-array', label: 'Balloon values', min: 1, max: 8 } }, defaultInput: { nums: [3, 1, 5, 8] }, samples: [{ input: { nums: [3, 1, 5, 8] }, expected: 167 }, { input: { nums: [1, 5] }, expected: 10 }], run: function* ({ nums }, L) { const n = nums.length, a = [1, ...nums, 1], dp = Array(n + 2).fill(0).map(() => Array(n + 2).fill(0)); for (let len = 1; len <= n; len++) { for (let l = 1; l + len - 1 <= n; l++) { const r = l + len - 1; for (let k = l; k <= r; k++) { const coins = a[l - 1] * a[k] * a[r + 1] + dp[l][k - 1] + dp[k + 1][r]; dp[l][r] = Math.max(dp[l][r], coins); yield { line: L('dp[l][r] = max(dp[l][r], coins);'), event: 'fill-cell', state: tableState(dp, [l, r]), vars: { l, r, k, value: dp[l][r] }, note: `Choose balloon ${k} as the last burst in interval [${l}, ${r}].` }; } } } const result = dp[1][n]; yield { line: L('return dp[1][n];'), event: 'done', state: tableState(dp), vars: { result }, note: `Maximum coins: ${result}.`, result }; } };

export const stockCooldown: TraceModule<{ prices: number[] }> = { renderer: 'dp-table', inputSchema: { prices: { type: 'int-array', label: 'Prices', min: 0, max: 16 } }, defaultInput: { prices: [1, 2, 3, 0, 2] }, samples: [{ input: { prices: [1, 2, 3, 0, 2] }, expected: 3 }, { input: { prices: [1] }, expected: 0 }], run: function* ({ prices }, L) { let held = -Infinity, sold = 0, rest = 0; const states: number[][] = []; for (const price of prices) { const prevSold = sold; sold = held + price; held = Math.max(held, rest - price); rest = Math.max(rest, prevSold); states.push([held, sold, rest]); yield { line: L('held = max(held, rest - price);'), event: 'calc', state: tableState(states), vars: { price, held, sold, rest }, note: 'Update holding, just-sold, and cooldown-cleared states.' }; } const result = Math.max(sold, rest); yield { line: L('return max(sold, rest);'), event: 'done', state: tableState(states), vars: { result }, note: `Maximum cooldown profit: ${result}.`, result }; } };

export const stockIII: TraceModule<{ prices: number[] }> = { renderer: 'dp-table', inputSchema: { prices: { type: 'int-array', label: 'Prices', min: 0, max: 16 } }, defaultInput: { prices: [3, 3, 5, 0, 0, 3, 1, 4] }, samples: [{ input: { prices: [3, 3, 5, 0, 0, 3, 1, 4] }, expected: 6 }, { input: { prices: [1, 2, 3, 4, 5] }, expected: 4 }], run: function* ({ prices }, L) { let buy1 = -Infinity, sell1 = 0, buy2 = -Infinity, sell2 = 0; const states: number[][] = []; for (const price of prices) { buy1 = Math.max(buy1, -price); sell1 = Math.max(sell1, buy1 + price); buy2 = Math.max(buy2, sell1 - price); sell2 = Math.max(sell2, buy2 + price); states.push([buy1, sell1, buy2, sell2]); yield { line: L('sell2 = max(sell2, buy2 + price);'), event: 'calc', state: tableState(states), vars: { price, buy1, sell1, buy2, sell2 }, note: 'Advance the four states for at most two transactions.' }; } yield { line: L('return sell2;'), event: 'done', state: tableState(states), vars: { result: sell2 }, note: `Maximum two-transaction profit: ${sell2}.`, result: sell2 }; } };
